config/routes.rb
require 'api_constraints'

Foreman::Application.routes.draw do
  #ENC requests goes here
  match "node/:name" => 'hosts#externalNodes', :constraints => { :name => /[^\.][\w\.-]+/ }
  post "reports/create"
  post "fact_values/create"

  resources :reports, :only => [:index, :show, :destroy, :create] do
    collection do
      get 'auto_complete_search'
    end
  end

  match '(:controller)/help', :action => 'welcome', :as => "help"
  constraints(:id => /[^\/]+/) do
    resources :hosts do
      member do
        get 'clone'
        get 'storeconfig_klasses'
        get 'externalNodes'
        get 'setBuild'
        get 'cancelBuild'
        get 'puppetrun'
        get 'pxe_config'
        put 'toggle_manage'
        post 'environment_selected'
        put 'power'
        get 'console'
        get 'bmc'
        put 'ipmi_boot'
      end
      collection do
        get 'multiple_actions'
        get 'multiple_parameters'
        post 'update_multiple_parameters'
        get 'select_multiple_hostgroup'
        post 'update_multiple_hostgroup'
        get 'select_multiple_environment'
        post 'update_multiple_environment'
        get 'multiple_puppetrun'
        post 'update_multiple_puppetrun'
        get 'multiple_destroy'
        post 'submit_multiple_destroy'
        get 'multiple_build'
        post 'submit_multiple_build'
        get 'reset_multiple'
        get 'multiple_disable'
        post 'submit_multiple_disable'
        get 'multiple_enable'
        post 'submit_multiple_enable'
        get 'auto_complete_search'
        get 'template_used'
        get 'active'
        get 'pending'
        get 'out_of_sync'
        get 'errors'
        get 'disabled'
        post 'current_parameters'
        post 'puppetclass_parameters'
        post 'process_hostgroup'
        post 'process_taxonomy'
        post 'hostgroup_or_environment_selected'
        post 'architecture_selected'
        post 'os_selected'
        post 'domain_selected'
        post 'use_image_selected'
        post 'compute_resource_selected'
        post 'medium_selected'
        get  'select_multiple_organization'
        post 'update_multiple_organization'
        get  'select_multiple_location'
        post 'update_multiple_location'
      end

      constraints(:host_id => /[^\/]+/) do
        resources :reports       ,:only => [:index, :show]
        resources :audits        ,:only => :index
        resources :facts         ,:only => :index, :controller => :fact_values
        resources :puppetclasses ,:only => :index
        resources :lookup_keys   ,:only => :show
      end
    end


    resources :bookmarks, :except => [:show]
    resources :lookup_keys, :except => [:new, :create] do
      resources :lookup_values, :only => [:index, :create, :update, :destroy]
      collection do
        get 'auto_complete_search'
      end
    end

    resources :facts, :only => [:index, :show] do
      constraints(:id => /[^\/]+/) do
        resources :values, :only => :index, :controller => :fact_values, :as => "host_fact_values"
      end
    end

  end

  resources :settings, :only => [:index, :update] do
    collection do
      get 'auto_complete_search'
    end
  end
  resources :common_parameters do
    collection do
      get 'auto_complete_search'
    end
  end
  resources :environments do
    collection do
      get 'import_environments'
      post 'obsolete_and_new'
      get 'auto_complete_search'
    end
  end
  resources :trends do
    collection do
      post 'count'
    end
  end

  resources :hostgroups do
    member do
      get 'nest'
      get 'clone'
    end
    collection do
      get 'auto_complete_search'
      post 'environment_selected'
      post 'architecture_selected'
      post 'os_selected'
      post 'domain_selected'
      post 'use_image_selected'
      post 'medium_selected'
      post 'process_hostgroup'
    end
  end

  resources :puppetclasses do
    collection do
      get 'import_environments'
      post 'obsolete_and_new'
      get 'auto_complete_search'
    end
    member do
      post 'parameters'
    end
    constraints(:id => /[^\/]+/) do
      resources :hosts
      resources :lookup_keys, :except => [:show, :new, :create]
    end
  end


  resources :smart_proxies, :except => [:show] do
    member do
      post 'ping'
    end
    constraints(:id => /[^\/]+/) do
      resources :puppetca, :only => [:index, :update, :destroy]
      resources :autosign, :only => [:index, :new, :create, :destroy]
    end
  end

  resources :fact_values, :only => [:index] do
    collection do
      get 'auto_complete_search'
    end
  end

  resources :notices, :only => :destroy
  resources :audits do
    collection do
      get 'auto_complete_search'
    end
  end

  if SETTINGS[:login]
    resources :usergroups
    resources :users, :except => [:show] do
      collection do
        get 'login'
        post 'login'
        get 'logout'
        get 'auth_source_selected'
        get 'auto_complete_search'
      end
    end
    resources :roles do
      collection do
        get 'report'
        post 'report'
        get 'auto_complete_search'
      end
    end

    resources :auth_source_ldaps
  end

  if SETTINGS[:unattended]
    resources :config_templates do
      collection do
        get 'auto_complete_search'
        get 'build_pxe_default'
        get 'revision'
      end
    end
    constraints(:id => /[^\/]+/) do
      resources :domains do
        collection do
          get 'auto_complete_search'
        end
      end
    end

    resources :operatingsystems do
      member do
        get 'bootfiles'
      end
      collection do
        get 'auto_complete_search'
      end
    end
    resources :media do
      collection do
        get 'auto_complete_search'
      end
    end

    resources :models do
      collection do
        get 'auto_complete_search'
      end
    end

    resources :architectures do
      collection do
        get 'auto_complete_search'
      end
    end

    resources :ptables do
      collection do
        get 'auto_complete_search'
      end
    end

    constraints(:id => /[^\/]+/) do
      resources :compute_resources do
        member do
          post 'hardware_profile_selected'
          post 'cluster_selected'
          post 'ping'
        end
        constraints(:id => /[^\/]+/) do
          resources :vms, :controller => "compute_resources_vms" do
            member do
              put 'power'
              get 'console'
            end
          end
        end
        collection do
          get  'auto_complete_search'
          get 'provider_selected'
          put  'test_connection'
        end
        resources :images
      end
    end

    resources :subnets, :except => [:show] do
      collection do
        get 'auto_complete_search'
        get 'import'
        post 'create_multiple'
        post 'freeip'
      end
    end

    match 'unattended/template/:id/:hostgroup', :to => "unattended#template"
  end

  root :to => 'dashboard#index'
  match 'dashboard', :to => 'dashboard#index', :as => "dashboard"
  match 'dashboard/auto_complete_search', :to => 'hosts#auto_complete_search', :as => "auto_complete_search_dashboards"
  match 'statistics', :to => 'statistics#index', :as => "statistics"
  match 'status', :to => 'home#status', :as => "status"

  # match for all unattended scripts
  match 'unattended/(:action/(:id(.format)))', :controller => 'unattended'

  resources :tasks, :only => [:show]

  if SETTINGS[:locations_enabled]
    resources :locations do
      resources :hosts, :only => :index
      member do
        get 'select'
        match "clone" => 'locations#clone_taxonomy'
        post 'import_mismatches'
        get 'step2'
        get 'assign_hosts'
        post 'assign_all_hosts'
        put 'assign_selected_hosts'
      end
      collection do
        get 'auto_complete_search'
        get 'clear'
        get  'mismatches'
        post 'import_mismatches'
      end
    end
  end

  if SETTINGS[:organizations_enabled]
    resources :organizations do
      member do
        get 'select'
        match "clone" => 'organizations#clone_taxonomy'
        post 'import_mismatches'
        get 'step2'
        get 'assign_hosts'
        post 'assign_all_hosts'
        put 'assign_selected_hosts'
      end
      collection do
        get 'auto_complete_search'
        get 'clear'
        get  'mismatches'
        post 'import_mismatches'
      end
    end
  end

  resources :about, :only => :index do
  end

end

app/controllers/api/v1/home_controller.rb
module Api
  module V1
    class HomeController < V1::BaseController
      before_filter :require_admin

      api :GET, "/", "Show available links."

      def index
        # we need to load apipie documentation to show all the links.
        Apipie.reload_documentation if Apipie.configuration.reload_controllers?
      end

      api :GET, "/status/", "Show status."

      def status
      end

      def route_error
        render_error 'route_error', :status => :not_found
      end

    end
  end
end

app/controllers/home_controller.rb
class HomeController < ApplicationController
  skip_before_filter :require_login, :only => [:status]
  skip_before_filter :authorize, :set_taxonomy, :only => [:status]
  skip_before_filter :session_expiry, :update_activity_time, :only => :status

  def settings
  end

  def status
    respond_to do |format|
      format.json do
        # make fake db call, measure duration and report errors
        result = exception_watch { User.first }
        render :json => result, :status => result[:status]
      end
      format.all { invalid_request }
    end
  end

  private
  # check for exception - set the result code and duration time
  def exception_watch &block
    start = Time.now
    result = {}
    yield
    result[:result] = 'ok'
    result[:status] = 200
    result[:version] = SETTINGS[:version]
    result[:db_duration_ms] = ((Time.now - start) * 1000).round.to_s
  rescue Exception => e
    result[:result] = 'fail'
    result[:status] = 500
    result[:message] = e.message
  ensure
    return result
  end
end

app/helpers/home_helper.rb
module HomeHelper

  def class_for_setting_page
    setting_options.flatten.include?(controller_name.to_sym) ? "active" : ""
  end

  def setting_options
    authorized_menu_actions(settings_menu_items)+[[_('About'), :about]]
  end

  def settings_menu_items
    configuration_group =
        [[_('Environments'),          :environments],
        [_('Global Parameters'),      :common_parameters],
        [_('Host Groups'),            :hostgroups],
        [_('Puppet Classes'),         :puppetclasses],
        [_('Smart Variables'),        :lookup_keys],
        [_('Smart Proxies'),          :smart_proxies]]
    menu_items = [ [:group, _("Configuration"), configuration_group]]

    if SETTINGS[:unattended]
      provisioning_group =
          [[_('Architectures'),          :architectures],
          [_('Compute Resources'),      :compute_resources],
          [_('Domains'),                :domains],
          [_('Hardware Models'),        :models],
          [_('Installation Media'),     :media],
          [_('Operating Systems'),      :operatingsystems],
          [_('Partition Tables'),       :ptables],
          [_('Provisioning Templates'), :config_templates],
          [_('Subnets'),                :subnets]]
      menu_items += [[:divider], [:group, _("Provisioning"), provisioning_group]]
    end

    if (SETTINGS[:organizations_enabled] or SETTINGS[:locations_enabled])
      menu_items += [[:divider]]
      menu_items += [ [_('Locations'), :locations] ]         if SETTINGS[:locations_enabled]
      menu_items += [ [_('Organizations'), :organizations] ] if SETTINGS[:organizations_enabled]
    end

    users_group =
      [[_('LDAP Authentication'),    :auth_source_ldaps],
      [_('Users'),                  :users],
      [_('User Groups'),            :usergroups]]
    users_group += [[_('Roles'),     :roles]] if User.current && User.current.admin?

    menu_items += [[:divider], [:group, _("Users"), users_group] ] if SETTINGS[:login]

    menu_items += [
      [:divider],
      [_('Bookmarks'),              :bookmarks],
      [_('Settings'),               :settings]
    ]
    menu_items
  end

  def authorized_menu_actions(choices)
    last_item = nil
    choices = choices.map do |item|
      #prevent adjacent dividers
      if item == [:divider]
        if last_item
          last_item = nil
          item
        end
      elsif item.size == 2 && authorized_for(item[1], :index)
        last_item = item
        item
      elsif item.size == 3
        item[2] = item[2].map do |sub_item|
          sub_item if authorized_for(sub_item[1], :index)
        end.compact
        if item[2].size > 0
          last_item = item
          item
        end
      end
    end.compact
    choices.pop if (choices.last == [:divider])
    choices
  end

  def menu(tab, label, path = nil)
    path ||= send("hash_for_#{tab}_path")
    return '' unless authorized_for(path[:controller], path[:action] )
    content_tag(:li, :class => "menu_tab_#{tab} ") do
      link_to_if_authorized(label, path)
    end
  end

  def org_switcher_title
    title = if Organization.current && Location.current
      Organization.current.to_label + "@" + Location.current.to_label
    elsif Organization.current
      Organization.current.to_label
    elsif Location.current
      Location.current.to_label
    else
      _("Any Context")
    end
    title
  end

  # filters out any non allowed actions from the setting menu.
  def allowed_choices choices, action = "index"
    choices.map do |opt|
      name, kontroller = opt
      url = send("#{kontroller}_url")
      authorized_for(kontroller, action) ? [name, url] : nil
    end.compact.sort
  end

  def user_header
    summary = gravatar_image_tag(User.current.mail, :class=>'gravatar small', :alt=>_('Change your avatar at gravatar.com')) +
              "#{User.current.to_label} " + content_tag(:span, "", :class=>'caret')
    link_to(summary.html_safe, "#", :class => "dropdown-toggle", :'data-toggle'=>"dropdown")
  end

end

app/views/home/_location_dropdown.html.erb
<li class="nav-header"><%= _('Location') %></li>
<li class="dropdown-submenu">
  <% location_count = Location.my_locations.count %>
  <%= location_dropdown location_count %>
  <ul class="dropdown-menu">
    <% if User.current.admin? %>
      <li><%= link_to(_('Any Location'), clear_locations_path) %></li>
      <%= content_tag(:li, "", :class=>"divider") %>
    <% end %>
    <% Location.my_locations.each do |location| %>
      <li><%= link_to(location.name, select_location_path(location)) %></li>
    <% end %>
  </ul>
</li>
<% if User.current.allowed_to?(:create_locations) %>
  <li><%= link_to _("Manage Locations"), locations_path, :class=> "manage-menu" %></li>
<% end %>

app/views/home/_org_switcher.html.erb
<% if SETTINGS[:locations_enabled] || SETTINGS[:organizations_enabled] %>
  <li class="dropdown org-switcher" >
    <a href="#" class ="dropdown-toggle" data-toggle="dropdown" ><%= org_switcher_title %><span class="caret"></span></a>

    <ul class="dropdown-menu">
      <%= render 'home/organization_dropdown' if SETTINGS[:organizations_enabled] %>
      <%= content_tag(:li,"",:class=>"divider") if SETTINGS[:organizations_enabled] && SETTINGS[:locations_enabled] %>
      <%= render 'home/location_dropdown' if SETTINGS[:locations_enabled] %>
    </ul>
  </li>
<% end %>

app/views/home/_organization_dropdown.html.erb
<li class="nav-header"><%= _('Organization') %></li>
<li class="dropdown-submenu">
  <% orgs_count = Organization.my_organizations.count %>
  <%= organization_dropdown orgs_count %>
  <ul class="dropdown-menu">
    <% if User.current.admin? %>
      <li><%= link_to(_('Any Organization'), clear_organizations_path) %></li>
      <%= content_tag(:li, "", :class => "divider") %>
    <% end %>
    <% Organization.my_organizations.each do |organization| %>
      <li><%= link_to(organization.name, select_organization_path(organization)) %></li>
    <% end %>
  </ul>
</li>
<% if User.current.allowed_to?(:create_organizations) %>
  <li><%= link_to _("Manage Organizations"), organizations_path, :class => "manage-menu" %></li>
<% end %>

app/views/home/_settings.html.erb
<li class="dropdown menu_tab_settings">
<% choices = setting_options %>
<%= link_to (_("More") + content_tag(:span,'', :class=>"caret")).html_safe, "#", :class => "dropdown-toggle", :'data-toggle'=>"dropdown" unless choices.empty?%>
  <ul class="dropdown-menu">
    <% choices.each do |item|-%>
       <% if item[0] == :divider  %>
         <%= content_tag(:li, "", :class=>"divider") %>
       <% elsif item[0] == :group %>
         <%= content_tag :li, :class=>"dropdown-submenu" do %>
           <%= link_to(item[1],"#",:class=>"dropdown-toggle", :"data-toggle"=>"dropdown") %>
           <%=  content_tag :ul, :class=>"dropdown-menu" do%>
             <% item[2].each do |sub_item|-%>
               <%= content_tag(:li, link_to(sub_item[0], {:controller => "/#{sub_item[1]}", :action => :index})) %>
             <% end %>
           <% end %>
         <% end %>
       <% else %>
         <%= content_tag(:li, link_to(item[0], {:controller => "/#{item[1]}", :action => :index})) %>
       <% end -%>
    <% end -%>
  </ul>
</li>

app/views/home/_topbar.html.erb
<!-- .btn-navbar is used as the toggle for collapsed navbar content -->
<a class="btn btn-navbar" data-toggle="collapse" data-target=".nav1">
  <span class="icon-bar"></span>
  <span class="icon-bar"></span>
  <span class="icon-bar"></span>
</a>
<a class="btn btn-navbar" style="padding: 5px 11px 2px 11px;" data-toggle="collapse" data-target=".nav2">
  <span class="icon-cog icon-white"></span>
</a>
<!-- menu -->
<div id='current_tab' data-controller='<%=controller_name.gsub(/_.*/,"s")%>' data-settings='<%= class_for_setting_page %>'> </div>

<% if User.current -%>
  <% cache(TopbarSweeper.fragment_name) do %>
    <div class="nav-collapse collapse nav1">
      <ul class="nav" id="menu">
      <%= render "home/org_switcher" %>
      <%= menu 'dashboard', _('Dashboard') %>
      <%= menu 'hosts', _('Hosts') %>
      <%= menu 'reports', _('Reports'), hash_for_reports_path.merge(:search => 'eventful = true') %>
      <%= menu 'facts' , _('Facts'), hash_for_fact_values_path %>
      <%= menu 'audits', _('Audits'), hash_for_audits_path %>
      <%= menu 'statistics', _('Statistics') %>
      <%= menu 'trends', _('Trends'), hash_for_trends_path %>
    </ul>
  </div>
  <div class="nav-collapse collapse nav2">
    <ul class="nav pull-right" id="menu2">
      <%= render "home/settings" -%>
    </ul>
  </div>
  <% end -%>
<% end -%>

app/views/home/_user_dropdown.html.erb
<ul class="nav pull-right ">
  <li class="dropdown">
    <%= user_header %>
    <ul class="dropdown-menu pull-right">
      <li><%= link_to(_("Sign Out"), logout_users_path) %></li>
      <li><%= link_to(_("My account"), edit_user_path(User.current) )%></li>
    </ul>
  </li>
</ul>